apiVersion: v1
kind: Service
metadata:
  name: pat-week12jenkins-service
spec:
  selector:
    app: pat-week12jenkins
  ports:
    - port: 8080           # Port exposed by the Service
      targetPort: 8080      # Port on the container
      nodePort: 30271     # Specific NodePort for external access
  type: NodePort        # Exposes the service outside the cluster